# Generated by Django 4.2.11 on 2024-05-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaction_category_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
