# Generated by Django 5.2.7 on 2026-07-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='openai_key',
        ),
    ]
