# Generated by Django 5.2.7 on 2026-07-22 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_recurringtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='t212_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='t212_api_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='t212_environment',
            field=models.CharField(choices=[('live', 'Live'), ('demo', 'Demo')], default='live', max_length=4),
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('positions', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_portfolio_snapshot_per_day')],
            },
        ),
    ]
