# Generated by Django 5.2.7 on 2026-07-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_backfill_account_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='llm_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio')], default='openai', max_length=16),
        ),
        migrations.AddField(
            model_name='settings',
            name='lmstudio_base_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='ollama_base_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
