# Generated by Django 5.2.7 on 2026-07-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_settings_anthropic_api_key_settings_llm_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='base_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='base_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=3)),
                ('quote', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base', 'quote', 'date'), name='unique_exchange_rate_per_day')],
            },
        ),
    ]
