# Generated by Django 5.2.7 on 2026-07-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_display_and_entry_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='telegram_allowed_user_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
