# Generated by Django 5.2.7 on 2026-07-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_settings_telegram_allowed_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
