"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import sys

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Desktop mode: the Tauri launcher sets FINTRAX_DATA_DIR to a per-user
# writable directory. When it's absent we're running the normal dev/web
# server and everything below falls back to the original behavior.
DATA_DIR = os.environ.get("FINTRAX_DATA_DIR")
DESKTOP_MODE = bool(DATA_DIR)


def _frontend_dist_dir():
    """Location of the built React app.

    In a PyInstaller onefile bundle the dist is unpacked under _MEIPASS;
    in a plain checkout it lives at repo_root/frontend/dist.
    """
    base = Path(getattr(sys, "_MEIPASS", BASE_DIR.parent))
    return base / "frontend" / "dist"


# Uppercase so it's exposed on django.conf.settings (LazySettings only
# proxies uppercase names). Used by WhiteNoise and the SPA catch-all view.
FRONTEND_DIST_DIR = _frontend_dist_dir()

# Idle timeout (seconds) after which an unlocked vault drops its in-memory DEK
# and the user must re-enter their master password. 0 disables idle re-locking.
VAULT_IDLE_TIMEOUT_SECONDS = 15 * 60


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if DESKTOP_MODE:
    from django.core.management.utils import get_random_secret_key

    _key_file = Path(DATA_DIR) / "secret_key.txt"
    Path(DATA_DIR).mkdir(parents=True, exist_ok=True)
    if _key_file.exists():
        SECRET_KEY = _key_file.read_text().strip()
    else:
        SECRET_KEY = get_random_secret_key()
        _key_file.write_text(SECRET_KEY)
else:
    SECRET_KEY = "django-insecure-(wd-ecmggr!qxq&ey+pbj1%!^yva2v0&du874@5vvc-x*oat!1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not DESKTOP_MODE

ALLOWED_HOSTS = ["127.0.0.1", "localhost"] if DESKTOP_MODE else ["*"]

CSRF_TRUSTED_ORIGINS = (
    ["http://127.0.0.1:8765", "http://localhost:8765"] if DESKTOP_MODE else []
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "api.auth.VaultJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Only the two credential endpoints opt in (via ScopedRateThrottle +
    # throttle_scope); everything else stays unthrottled. Login also unwraps the
    # vault DEK, so an unthrottled /api/token/ is a brute-force path at the
    # encryption itself. Keyed by client IP (requests are anonymous).
    "DEFAULT_THROTTLE_RATES": {
        "login": "10/min",
        "recover": "5/min",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "api",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "api.middleware.VaultMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": (Path(DATA_DIR) / "db.sqlite3") if DESKTOP_MODE else BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

if DESKTOP_MODE:
    # Collected admin/DRF assets live in the per-user data dir; WhiteNoise
    # additionally serves the built React app (index.html, /assets/*) from
    # the site root so the sidecar is fully self-contained.
    STATIC_ROOT = Path(DATA_DIR) / "staticfiles"
    WHITENOISE_ROOT = FRONTEND_DIST_DIR
    WHITENOISE_INDEX_FILE = True
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# The desktop webview loads the SPA from the sidecar's own origin
# (http://127.0.0.1:<port>), so every API call is same-origin and needs no CORS
# grant — allowing all origins there is pure attack surface (any site the user
# visits could script the local API). The dev/web build serves the SPA from a
# separate Vite origin, so it still needs cross-origin access. Auth is a JWT in
# the Authorization header, not a cookie, so credentialed CORS isn't needed.
CORS_ALLOW_ALL_ORIGINS = not DESKTOP_MODE
